using System.Text;
using static TerminalHyperspace.Importer.Parsers;

namespace TerminalHyperspace.Importer;

public class Emitter
{
    private readonly ImportContext _ctx;
    private readonly string _outDir;

    private static readonly string[] Attrs =
        { "Dexterity", "Knowledge", "Mechanical", "Perception", "Strength", "Technical", "Force" };

    private const string Header =
        "// <auto-generated/>\n" +
        "// Generated by th-import. Do not edit by hand — re-run the importer to regenerate.\n";

    public Emitter(ImportContext ctx, string outDir)
    {
        _ctx = ctx;
        _outDir = outDir;
    }

    public int EmitAll()
    {
        int total = 0;
        total += EmitItems();
        total += EmitArmorAndShields();
        total += EmitVehicles();
        total += EmitNPCs();
        total += EmitSpaceEncounters();
        total += EmitSpecies();
        total += EmitRoles();
        total += EmitSkillChecks();
        total += EmitLocations();
        return total;
    }

    private void Write(string fileName, string content)
        => File.WriteAllText(Path.Combine(_outDir, fileName), content);

    // =================================================================
    // Items
    // =================================================================
    private int EmitItems()
    {
        if (_ctx.Items.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class ItemData");
        sb.AppendLine("{");
        foreach (var r in _ctx.Items)
        {
            var id = r.Get("Id");
            var isWeapon = ParseBool(r.Get("IsWeapon"));
            var isCons = ParseBool(r.Get("IsConsumable"));
            sb.AppendLine($"    public static Item {id} => new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        Name = {Quote(r.Get("Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Description")))
                sb.AppendLine($"        Description = {Quote(r.Get("Description"))},");
            sb.AppendLine($"        IsWeapon = {(isWeapon ? "true" : "false")},");
            if (isWeapon)
            {
                sb.AppendLine($"        Damage = {DiceLiteral(r.Get("Damage"))},");
                if (!string.IsNullOrEmpty(r.Get("AttackSkill")))
                    sb.AppendLine($"        AttackSkill = SkillType.{r.Get("AttackSkill")},");
                sb.AppendLine($"        Range = {ParseInt(r.Get("Range"))},");
            }
            sb.AppendLine($"        Price = {ParseInt(r.Get("Price"))},");
            if (isCons) sb.AppendLine("        IsConsumable = true,");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        Write("ItemData.Generated.cs", sb.ToString());
        return _ctx.Items.Count;
    }

    // =================================================================
    // Armor + Shields
    // =================================================================
    private int EmitArmorAndShields()
    {
        int n = 0;
        if (_ctx.Armor.Count > 0)
        {
            var sb = new StringBuilder();
            sb.Append(Header);
            sb.AppendLine("using TerminalHyperspace.Models;");
            sb.AppendLine();
            sb.AppendLine("namespace TerminalHyperspace.Content;");
            sb.AppendLine();
            sb.AppendLine("public static partial class ArmorData");
            sb.AppendLine("{");
            foreach (var r in _ctx.Armor)
            {
                var id = r.Get("Id");
                sb.AppendLine($"    public static readonly Armor {id} = new()");
                sb.AppendLine("    {");
                sb.AppendLine($"        Name = {Quote(r.Get("Name"))},");
                sb.AppendLine($"        DiceCode = {DiceLiteral(r.Get("DiceCode"))},");
                sb.AppendLine($"        Price = {ParseInt(r.Get("Price"))},");
                var clim = r.Get("Climate");
                if (!string.IsNullOrEmpty(clim) && !clim.Equals("Normal", StringComparison.OrdinalIgnoreCase))
                    sb.AppendLine($"        Climate = Climate.{clim},");
                sb.AppendLine("    };");
                sb.AppendLine();
                n++;
            }
            sb.AppendLine("}");
            Write("ArmorData.Generated.cs", sb.ToString());
        }
        if (_ctx.Shields.Count > 0)
        {
            var sb = new StringBuilder();
            sb.Append(Header);
            sb.AppendLine("using TerminalHyperspace.Models;");
            sb.AppendLine();
            sb.AppendLine("namespace TerminalHyperspace.Content;");
            sb.AppendLine();
            sb.AppendLine("public static partial class ShieldData");
            sb.AppendLine("{");
            foreach (var r in _ctx.Shields)
            {
                var id = r.Get("Id");
                sb.AppendLine($"    public static readonly VehicleShield {id} = new()");
                sb.AppendLine("    {");
                sb.AppendLine($"        Name = {Quote(r.Get("Name"))},");
                sb.AppendLine($"        DiceCode = {DiceLiteral(r.Get("DiceCode"))},");
                sb.AppendLine($"        Price = {ParseInt(r.Get("Price"))},");
                sb.AppendLine("    };");
                sb.AppendLine();
                n++;
            }
            sb.AppendLine("}");
            Write("ShieldData.Generated.cs", sb.ToString());
        }
        return n;
    }

    // =================================================================
    // Vehicles
    // =================================================================
    private int EmitVehicles()
    {
        if (_ctx.Vehicles.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class VehicleData");
        sb.AppendLine("{");
        foreach (var r in _ctx.Vehicles)
        {
            sb.AppendLine($"    public static Vehicle {r.Get("Id")} => new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        Name = {Quote(r.Get("Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Description")))
                sb.AppendLine($"        Description = {Quote(r.Get("Description"))},");
            sb.AppendLine($"        IsSpace = {(ParseBool(r.Get("IsSpace")) ? "true" : "false")},");
            sb.AppendLine($"        Maneuverability = {DiceLiteral(r.Get("Maneuverability"))},");
            sb.AppendLine($"        Resolve = {ParseInt(r.Get("Resolve"))},");
            var shield = r.Get("Shield");
            if (!string.IsNullOrEmpty(shield)) sb.AppendLine($"        Shield = ShieldData.{shield},");
            EmitVehicleWeapons(sb, r.Get("Weapons"), indent: "        ");
            EmitVehicleEquipment(sb, r.Get("Equipment"), indent: "        ");
            sb.AppendLine($"        Price = {ParseInt(r.Get("Price"))},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        Write("VehicleData.Generated.cs", sb.ToString());
        return _ctx.Vehicles.Count;
    }

    private static void EmitVehicleWeapons(StringBuilder sb, string raw, string indent)
    {
        var tuples = SplitTuples(raw);
        if (tuples.Count == 0) return;
        sb.AppendLine($"{indent}Weapons = new()");
        sb.AppendLine($"{indent}{{");
        foreach (var t in tuples)
        {
            if (t.Length < 3) continue;
            sb.AppendLine($"{indent}    new() {{ Name = {Quote(t[0])}, Damage = {DiceLiteral(t[1])}, AttackSkill = SkillType.{t[2]} }},");
        }
        sb.AppendLine($"{indent}}},");
    }

    private static void EmitVehicleEquipment(StringBuilder sb, string raw, string indent)
    {
        var tuples = SplitTuples(raw);
        if (tuples.Count == 0) return;
        sb.AppendLine($"{indent}Equipment = new()");
        sb.AppendLine($"{indent}{{");
        foreach (var t in tuples)
        {
            if (t.Length < 3) continue;
            sb.AppendLine($"{indent}    new() {{ Name = {Quote(t[0])}, BonusSkill = SkillType.{t[1]}, Bonus = {DiceLiteral(t[2])} }},");
        }
        sb.AppendLine($"{indent}}},");
    }

    // =================================================================
    // NPCs
    // =================================================================
    private int EmitNPCs()
    {
        if (_ctx.NPCs.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class NPCData");
        sb.AppendLine("{");
        foreach (var r in _ctx.NPCs)
        {
            EmitCharacterFactory(sb, r.Get("Id"), r, methodKind: "method");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        Write("NPCData.Generated.cs", sb.ToString());
        return _ctx.NPCs.Count;
    }

    /// Emits a Character factory. methodKind: "method" → public static Character X() => new() {...};
    /// "expr" → emits as inline `new Character { ... }` (used inside SpaceEncounters).
    private static void EmitCharacterFactory(StringBuilder sb, string id, Row r, string methodKind, string indent = "    ")
    {
        var name = r.Get("DisplayName");
        if (string.IsNullOrEmpty(name)) name = r.Get("Pilot.Name");
        if (string.IsNullOrEmpty(name)) name = id;

        if (methodKind == "method")
        {
            sb.AppendLine($"{indent}public static Character {id}() => new()");
            sb.AppendLine($"{indent}{{");
        }
        else
        {
            sb.AppendLine($"{indent}new Character");
            sb.AppendLine($"{indent}{{");
        }
        var inner = indent + "    ";
        sb.AppendLine($"{inner}Name = {Quote(name)},");
        sb.AppendLine($"{inner}IsPlayer = false,");
        sb.AppendLine($"{inner}Attributes = new()");
        sb.AppendLine($"{inner}{{");
        foreach (var a in Attrs)
        {
            var dice = r.Get(a);
            if (string.IsNullOrEmpty(dice)) dice = r.Get($"Pilot.{a}");
            if (string.IsNullOrEmpty(dice)) dice = "0D";
            sb.AppendLine($"{inner}    [AttributeType.{a}] = {DiceLiteral(dice)},");
        }
        sb.AppendLine($"{inner}}},");

        var skillBonusSrc = !string.IsNullOrEmpty(r.Get("SkillBonuses")) ? r.Get("SkillBonuses") : r.Get("Pilot.SkillBonuses");
        var bonuses = SplitKeyVal(skillBonusSrc);
        if (bonuses.Count > 0)
        {
            sb.AppendLine($"{inner}SkillBonuses = new()");
            sb.AppendLine($"{inner}{{");
            foreach (var (skill, dice) in bonuses)
                sb.AppendLine($"{inner}    [SkillType.{skill}] = {DiceLiteral(dice)},");
            sb.AppendLine($"{inner}}},");
        }

        var inv = SplitSemi(r.Get("Inventory"));
        if (inv.Count > 0)
        {
            sb.AppendLine($"{inner}Inventory = new() {{ {string.Join(", ", inv.Select(i => $"ItemData.{i}"))} }},");
        }

        var weapon = r.Get("EquippedWeapon");
        if (!string.IsNullOrEmpty(weapon))
            sb.AppendLine($"{inner}EquippedWeapon = ItemData.{weapon},");

        var armor = !string.IsNullOrEmpty(r.Get("EquippedArmor")) ? r.Get("EquippedArmor") : r.Get("Pilot.EquippedArmor");
        if (!string.IsNullOrEmpty(armor))
            sb.AppendLine($"{inner}EquippedArmor = ArmorData.{armor},");

        if (methodKind == "method")
            sb.AppendLine($"{indent}}};");
        else
            sb.AppendLine($"{indent}}}");
    }

    // =================================================================
    // SpaceEncounters
    // =================================================================
    private int EmitSpaceEncounters()
    {
        if (_ctx.SpaceEncounters.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SpaceEncounterData");
        sb.AppendLine("{");
        foreach (var r in _ctx.SpaceEncounters)
        {
            var id = r.Get("Id");
            sb.AppendLine($"    public static SpaceEncounter {id}() => new()");
            sb.AppendLine("    {");
            sb.AppendLine("        Pilot =");
            EmitCharacterFactory(sb, id, r, methodKind: "expr", indent: "            ");
            sb.AppendLine("        ,");

            sb.AppendLine("        Ship = new Vehicle");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = {Quote(r.Get("Ship.Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Ship.Description")))
                sb.AppendLine($"            Description = {Quote(r.Get("Ship.Description"))},");
            sb.AppendLine("            IsSpace = true,");
            sb.AppendLine($"            Maneuverability = {DiceLiteral(r.Get("Ship.Maneuverability"))},");
            sb.AppendLine($"            Resolve = {ParseInt(r.Get("Ship.Resolve"))},");
            var shield = r.Get("Ship.Shield");
            if (!string.IsNullOrEmpty(shield)) sb.AppendLine($"            Shield = ShieldData.{shield},");
            EmitVehicleWeapons(sb, r.Get("Ship.Weapons"), indent: "            ");
            EmitVehicleEquipment(sb, r.Get("Ship.Equipment"), indent: "            ");
            sb.AppendLine("        },");

            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        Write("SpaceEncounterData.Generated.cs", sb.ToString());
        return _ctx.SpaceEncounters.Count;
    }

    // =================================================================
    // Species
    // =================================================================
    private int EmitSpecies()
    {
        if (_ctx.Species.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SpeciesData");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterImported(List<Species> list)");
        sb.AppendLine("    {");
        foreach (var r in _ctx.Species)
        {
            sb.AppendLine("        list.Add(new Species");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = {Quote(r.Get("Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Description")))
                sb.AppendLine($"            Description = {Quote(r.Get("Description"))},");
            sb.AppendLine("            BaseAttributes = new()");
            sb.AppendLine("            {");
            foreach (var a in Attrs)
            {
                var dice = r.Get(a); if (string.IsNullOrEmpty(dice)) dice = "0D";
                sb.AppendLine($"                [AttributeType.{a}] = {DiceLiteral(dice)},");
            }
            sb.AppendLine("            },");
            var bonuses = SplitKeyVal(r.Get("SkillBonuses"));
            if (bonuses.Count > 0)
            {
                sb.AppendLine("            SkillBonuses = new()");
                sb.AppendLine("            {");
                foreach (var (skill, dice) in bonuses)
                    sb.AppendLine($"                [SkillType.{skill}] = {DiceLiteral(dice)},");
                sb.AppendLine("            },");
            }
            sb.AppendLine("        });");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        Write("SpeciesData.Generated.cs", sb.ToString());
        return _ctx.Species.Count;
    }

    // =================================================================
    // Roles
    // =================================================================
    private int EmitRoles()
    {
        if (_ctx.Roles.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class RoleData");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterImported(List<Role> list)");
        sb.AppendLine("    {");
        foreach (var r in _ctx.Roles)
        {
            sb.AppendLine("        list.Add(new Role");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = {Quote(r.Get("Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Description")))
                sb.AppendLine($"            Description = {Quote(r.Get("Description"))},");
            var attrs = SplitKeyVal(r.Get("AttributeBonuses"));
            if (attrs.Count > 0)
            {
                sb.AppendLine("            AttributeBonuses = new()");
                sb.AppendLine("            {");
                foreach (var (a, dice) in attrs)
                    sb.AppendLine($"                [AttributeType.{a}] = {DiceLiteral(dice)},");
                sb.AppendLine("            },");
            }
            var bonuses = SplitKeyVal(r.Get("SkillBonuses"));
            if (bonuses.Count > 0)
            {
                sb.AppendLine("            SkillBonuses = new()");
                sb.AppendLine("            {");
                foreach (var (skill, dice) in bonuses)
                    sb.AppendLine($"                [SkillType.{skill}] = {DiceLiteral(dice)},");
                sb.AppendLine("            },");
            }
            sb.AppendLine("        });");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        Write("RoleData.Generated.cs", sb.ToString());
        return _ctx.Roles.Count;
    }

    // =================================================================
    // SkillChecks
    // =================================================================
    private int EmitSkillChecks()
    {
        if (_ctx.SkillChecks.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SkillCheckData");
        sb.AppendLine("{");

        // Public per-row members so they can be referenced by Id elsewhere if needed.
        foreach (var r in _ctx.SkillChecks)
        {
            var id = ToPascal(r.Get("Id"));
            sb.AppendLine($"    public static SkillCheckEvent Imported_{id} => new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        Id = {Quote(r.Get("Id"))},");
            sb.AppendLine($"        Description = {Quote(r.Get("Description"))},");
            sb.AppendLine($"        SuccessText = {Quote(r.Get("SuccessText"))},");
            sb.AppendLine($"        FailText = {Quote(r.Get("FailText"))},");
            if (!string.IsNullOrEmpty(r.Get("FailPenaltyText")))
                sb.AppendLine($"        FailPenaltyText = {Quote(r.Get("FailPenaltyText"))},");
            sb.AppendLine($"        Skill = SkillType.{r.Get("Skill")},");
            var diff = string.IsNullOrEmpty(r.Get("Difficulty")) ? "Moderate" : r.Get("Difficulty");
            sb.AppendLine($"        Difficulty = CheckDifficulty.{diff},");
            sb.AppendLine($"        TargetNumber = {ParseInt(r.Get("TargetNumber"))},");
            sb.AppendLine($"        CreditReward = {ParseInt(r.Get("CreditReward"))},");
            sb.AppendLine($"        UpgradePointReward = {ParseInt(r.Get("UpgradePointReward"))},");
            if (ParseBool(r.Get("Repeatable")))
                sb.AppendLine("        Repeatable = true,");
            if (ParseInt(r.Get("CreditPenalty")) > 0)
                sb.AppendLine($"        CreditPenalty = {ParseInt(r.Get("CreditPenalty"))},");
            var combatNpc = r.Get("CombatNpcOnFail");
            if (!string.IsNullOrEmpty(combatNpc))
                sb.AppendLine($"        CombatNpcOnFail = NPCData.{combatNpc},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        // Hook: register into LocationChecks / TalkChecks
        sb.AppendLine("    static partial void RegisterImportedLocationChecks(Dictionary<string, List<SkillCheckEvent>> map)");
        sb.AppendLine("    {");
        var byLocation = _ctx.SkillChecks
            .Where(r => !ParseBool(r.Get("TalkCheck")) && !string.IsNullOrEmpty(r.Get("LocationId")))
            .GroupBy(r => r.Get("LocationId"));
        foreach (var grp in byLocation)
        {
            sb.AppendLine($"        if (!map.TryGetValue({Quote(grp.Key)}, out var list_{Sanitize(grp.Key)}))");
            sb.AppendLine($"            map[{Quote(grp.Key)}] = list_{Sanitize(grp.Key)} = new();");
            foreach (var r in grp)
                sb.AppendLine($"        list_{Sanitize(grp.Key)}.Add(Imported_{ToPascal(r.Get("Id"))});");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static partial void RegisterImportedTalkChecks(List<SkillCheckEvent> list)");
        sb.AppendLine("    {");
        foreach (var r in _ctx.SkillChecks.Where(r => ParseBool(r.Get("TalkCheck"))))
            sb.AppendLine($"        list.Add(Imported_{ToPascal(r.Get("Id"))});");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        Write("SkillCheckData.Generated.cs", sb.ToString());
        return _ctx.SkillChecks.Count;
    }

    // =================================================================
    // Locations
    // =================================================================
    private int EmitLocations()
    {
        if (_ctx.Locations.Count == 0) return 0;
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine("using TerminalHyperspace.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TerminalHyperspace.Content;");
        sb.AppendLine();
        sb.AppendLine("public static partial class LocationData");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterImported(Dictionary<string, Location> world)");
        sb.AppendLine("    {");
        foreach (var r in _ctx.Locations)
        {
            var id = r.Get("Id");
            sb.AppendLine($"        world[{Quote(id)}] = new Location");
            sb.AppendLine("        {");
            sb.AppendLine($"            Id = {Quote(id)},");
            sb.AppendLine($"            Name = {Quote(r.Get("Name"))},");
            if (!string.IsNullOrEmpty(r.Get("Description")))
                sb.AppendLine($"            Description = {Quote(r.Get("Description"))},");
            if (ParseBool(r.Get("IsSpace")))         sb.AppendLine("            IsSpace = true,");
            if (ParseBool(r.Get("IsSystemSpace")))   sb.AppendLine("            IsSystemSpace = true,");
            if (ParseBool(r.Get("RequiresVehicle"))) sb.AppendLine("            RequiresVehicle = true,");

            var clim = r.Get("Climate");
            if (!string.IsNullOrEmpty(clim) && !clim.Equals("Normal", StringComparison.OrdinalIgnoreCase))
                sb.AppendLine($"            Climate = Climate.{clim},");

            var coords = r.Get("HyperspaceCoordinates");
            if (!string.IsNullOrEmpty(coords))
            {
                var (x, y) = ParseCoords(coords);
                sb.AppendLine($"            HyperspaceCoordinates = new[] {{ {x}, {y} }},");
            }

            foreach (var f in new[] { "PlanetName", "StarSystemName", "SectorName", "TerritoryName" })
                if (!string.IsNullOrEmpty(r.Get(f)))
                    sb.AppendLine($"            {f} = {Quote(r.Get(f))},");

            var exits = SplitKeyVal(r.Get("Exits"));
            if (exits.Count > 0)
            {
                sb.AppendLine("            Exits = new()");
                sb.AppendLine("            {");
                foreach (var (dir, target) in exits)
                    sb.AppendLine($"                [{Quote(dir)}] = {Quote(target)},");
                sb.AppendLine("            },");
            }

            var encs = SplitSemi(r.Get("PossibleEncounters"));
            if (encs.Count > 0)
                sb.AppendLine($"            PossibleEncounters = new() {{ {string.Join(", ", encs.Select(n => $"NPCData.{n}"))} }},");

            if (!string.IsNullOrEmpty(r.Get("EncounterChance")))
                sb.AppendLine($"            EncounterChance = {ParseDouble(r.Get("EncounterChance")).ToString(System.Globalization.CultureInfo.InvariantCulture)},");

            var friendly = SplitSemi(r.Get("FriendlyNPCs"));
            if (friendly.Count > 0)
                sb.AppendLine($"            FriendlyNPCs = new() {{ {string.Join(", ", friendly.Select(n => $"NPCData.{n}"))} }},");

            if (ParseBool(r.Get("HasShop")))         sb.AppendLine("            HasShop = true,");
            if (ParseBool(r.Get("HasVehicleShop")))  sb.AppendLine("            HasVehicleShop = true,");

            var spaceEncs = SplitSemi(r.Get("SpaceEncounters"));
            if (spaceEncs.Count > 0)
                sb.AppendLine($"            SpaceEncounters = new() {{ {string.Join(", ", spaceEncs.Select(n => $"SpaceEncounterData.{n}"))} }},");

            if (!string.IsNullOrEmpty(r.Get("SpaceEncounterChance")))
                sb.AppendLine($"            SpaceEncounterChance = {ParseDouble(r.Get("SpaceEncounterChance")).ToString(System.Globalization.CultureInfo.InvariantCulture)},");

            var ambient = r.Get("AmbientMessages");
            if (!string.IsNullOrEmpty(ambient))
            {
                var lines = ambient.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                if (lines.Length > 0)
                {
                    sb.AppendLine("            AmbientMessages = new()");
                    sb.AppendLine("            {");
                    foreach (var line in lines)
                        sb.AppendLine($"                {Quote(line)},");
                    sb.AppendLine("            },");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        Write("LocationData.Generated.cs", sb.ToString());
        return _ctx.Locations.Count;
    }

    private static string Sanitize(string s)
        => new string(s.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    private static string ToPascal(string s)
    {
        var parts = s.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    }
}
